/**
 * AI Analysis TypeScript Types
 * Matching the backend analysis models from Phase 6
 *
 * These types represent the Warren Buffett-style investment memo
 * generated by the AI analyst service.
 */

/**
 * Investment Rating - Overall recommendation
 */
export type InvestmentRating =
  | "strong_buy"
  | "buy"
  | "hold"
  | "sell"
  | "strong_sell";

/**
 * Risk Level - Overall risk assessment
 */
export type RiskLevel = "low" | "moderate" | "high" | "very_high";

/**
 * Moat Type - Types of competitive advantages
 */
export type MoatType =
  | "brand"
  | "network_effects"
  | "cost_advantage"
  | "switching_costs"
  | "efficient_scale"
  | "intangible_assets"
  | "none";

/**
 * Competitive Advantage - Analysis of a single competitive moat
 */
export interface CompetitiveAdvantage {
  /** Type of moat */
  moat_type: MoatType;
  /** Description of the competitive advantage */
  description: string;
  /** Durability assessment: "narrow", "wide", "eroding" */
  durability: string;
  /** Evidence supporting the moat */
  evidence: string[];
  /** Confidence level (0.0 to 1.0) */
  confidence: number;
}

/**
 * Risk Factor - Detailed risk assessment
 */
export interface RiskFactor {
  /** Risk category: "market", "regulatory", "competitive", "operational", "financial" */
  category: string;
  /** Short title of the risk */
  title: string;
  /** Detailed description of the risk */
  description: string;
  /** Severity level: "low", "medium", "high", "critical" */
  severity: string;
  /** Probability: "unlikely", "possible", "likely", "very_likely" */
  probability: string;
  /** Potential mitigation strategy */
  mitigation: string | null;
}

/**
 * Warren Buffett Analysis - Complete AI-generated investment memo
 *
 * This comprehensive analysis combines quantitative valuation
 * with qualitative business assessment in Warren Buffett's style.
 */
export interface WarrenBuffettAnalysis {
  // === Header ===
  /** Stock ticker symbol */
  ticker: string;
  /** Company name */
  company_name: string;
  /** Date of analysis */
  analysis_date: string;

  // === Executive Summary ===
  /** One compelling sentence summarizing the investment case */
  one_sentence_thesis: string;
  /** 2-3 paragraph detailed investment thesis */
  investment_thesis: string;

  // === Business Quality Assessment ===
  /** Can I understand this business in 10 minutes? */
  business_understanding: string;
  /** Business simplicity score (1=highly complex, 10=simple and predictable) */
  business_simplicity_score: number;
  /** List of competitive advantages identified */
  competitive_advantages: CompetitiveAdvantage[];
  /** Summary of moat analysis */
  moat_summary: string;
  /** Overall moat durability: "none", "narrow", "wide" */
  moat_durability: string;

  // === Management Quality ===
  /** Assessment of management team */
  management_assessment: string;
  /** Management integrity score (1-10) */
  management_integrity_score: number;
  /** Capital allocation skill assessment */
  capital_allocation_skill: string;
  /** Whether management is owner-oriented */
  owner_oriented: boolean;

  // === Earnings Power ===
  /** Analysis of true cash-generating ability */
  owner_earnings_analysis: string;
  /** Earnings predictability: "highly_predictable", "predictable", "uncertain", "unpredictable" */
  earnings_predictability: string;

  // === Financial Health ===
  /** Balance sheet fortress assessment */
  balance_sheet_fortress: string;
  /** Debt comfort level assessment */
  debt_comfort_level: string;
  /** Cash generation power assessment */
  cash_generation_power: string;
  /** Return on capital trend assessment */
  return_on_capital_trend: string;

  // === Valuation Summary ===
  /** Narrative on valuation */
  valuation_narrative: string;
  /** Intrinsic value range (e.g., "$X to $Y") */
  intrinsic_value_range: string;
  /** Current price vs intrinsic value assessment */
  current_price_vs_value: string;
  /** Margin of safety assessment */
  margin_of_safety_assessment: string;

  // === Key Investment Considerations ===
  /** Main reasons to buy (3-7 items) */
  key_positives: string[];
  /** Main risks and concerns (2-5 items) */
  key_concerns: string[];
  /** Detailed risk factors */
  key_risks: RiskFactor[];
  /** Potential catalysts for value realization */
  potential_catalysts: string[];

  // === Time Horizon ===
  /** Ideal holding period: "3-5 years", "5-10 years", "forever" */
  ideal_holding_period: string;
  /** Patience required level assessment */
  patience_required_level: string;

  // === Final Verdict ===
  /** Overall investment rating */
  investment_rating: InvestmentRating;
  /** Confidence level in the rating (0.0 to 1.0) */
  conviction_level: number;
  /** Overall risk level */
  risk_level: RiskLevel;
  /** Suitable investor types: "value_investors", "dividend_seekers", "growth_investors", etc. */
  suitable_for: string[];

  // === Closing Wisdom ===
  /** Relevant Warren Buffett quote for this situation */
  buffett_quote: string;
  /** Final thoughts and conclusion */
  final_thoughts: string;

  // === Meta Information ===
  /** AI model used for generation */
  ai_model_used: string;
  /** Analysis version */
  analysis_version: string;
  /** Number of tokens consumed */
  tokens_consumed: number | null;
  /** Time taken to generate (in seconds) */
  generation_time_seconds: number | null;
}

/**
 * Get display properties for investment rating
 * Returns label and color classes for UI rendering
 */
export function getRatingDisplayProps(rating: InvestmentRating): {
  label: string;
  colorClass: string;
  bgClass: string;
  borderClass: string;
} {
  switch (rating) {
    case "strong_buy":
      return {
        label: "Strong Buy",
        colorClass: "text-emerald-400",
        bgClass: "bg-emerald-500/10",
        borderClass: "border-emerald-500/30",
      };
    case "buy":
      return {
        label: "Buy",
        colorClass: "text-green-400",
        bgClass: "bg-green-500/10",
        borderClass: "border-green-500/30",
      };
    case "hold":
      return {
        label: "Hold",
        colorClass: "text-yellow-400",
        bgClass: "bg-yellow-500/10",
        borderClass: "border-yellow-500/30",
      };
    case "sell":
      return {
        label: "Sell",
        colorClass: "text-orange-400",
        bgClass: "bg-orange-500/10",
        borderClass: "border-orange-500/30",
      };
    case "strong_sell":
      return {
        label: "Strong Sell",
        colorClass: "text-red-400",
        bgClass: "bg-red-500/10",
        borderClass: "border-red-500/30",
      };
    default:
      return {
        label: "Unknown",
        colorClass: "text-gray-400",
        bgClass: "bg-gray-500/10",
        borderClass: "border-gray-500/30",
      };
  }
}

/**
 * Get display properties for risk level
 * Returns label and color class for UI rendering
 */
export function getRiskLevelDisplayProps(level: RiskLevel): {
  label: string;
  colorClass: string;
  bgClass: string;
} {
  switch (level) {
    case "low":
      return {
        label: "Low Risk",
        colorClass: "text-emerald-400",
        bgClass: "bg-emerald-500/10",
      };
    case "moderate":
      return {
        label: "Moderate Risk",
        colorClass: "text-yellow-400",
        bgClass: "bg-yellow-500/10",
      };
    case "high":
      return {
        label: "High Risk",
        colorClass: "text-orange-400",
        bgClass: "bg-orange-500/10",
      };
    case "very_high":
      return {
        label: "Very High Risk",
        colorClass: "text-red-400",
        bgClass: "bg-red-500/10",
      };
    default:
      return {
        label: "Unknown",
        colorClass: "text-gray-400",
        bgClass: "bg-gray-500/10",
      };
  }
}

/**
 * Get human-readable label for moat type
 */
export function getMoatTypeLabel(type: MoatType): string {
  switch (type) {
    case "brand":
      return "Brand Power";
    case "network_effects":
      return "Network Effects";
    case "cost_advantage":
      return "Cost Advantage";
    case "switching_costs":
      return "Switching Costs";
    case "efficient_scale":
      return "Efficient Scale";
    case "intangible_assets":
      return "Intangible Assets";
    case "none":
      return "No Moat";
    default:
      return "Unknown";
  }
}

/**
 * Get display properties for moat durability
 */
export function getMoatDurabilityDisplayProps(durability: string): {
  label: string;
  colorClass: string;
  bgClass: string;
} {
  switch (durability.toLowerCase()) {
    case "wide":
      return {
        label: "Wide Moat",
        colorClass: "text-emerald-400",
        bgClass: "bg-emerald-500/10",
      };
    case "narrow":
      return {
        label: "Narrow Moat",
        colorClass: "text-yellow-400",
        bgClass: "bg-yellow-500/10",
      };
    case "eroding":
      return {
        label: "Eroding Moat",
        colorClass: "text-orange-400",
        bgClass: "bg-orange-500/10",
      };
    case "none":
      return {
        label: "No Moat",
        colorClass: "text-gray-400",
        bgClass: "bg-gray-500/10",
      };
    default:
      return {
        label: durability,
        colorClass: "text-gray-400",
        bgClass: "bg-gray-500/10",
      };
  }
}

/**
 * Get display properties for severity level
 */
export function getSeverityDisplayProps(severity: string): {
  label: string;
  colorClass: string;
  bgClass: string;
} {
  switch (severity.toLowerCase()) {
    case "low":
      return {
        label: "Low",
        colorClass: "text-green-400",
        bgClass: "bg-green-500/10",
      };
    case "medium":
      return {
        label: "Medium",
        colorClass: "text-yellow-400",
        bgClass: "bg-yellow-500/10",
      };
    case "high":
      return {
        label: "High",
        colorClass: "text-orange-400",
        bgClass: "bg-orange-500/10",
      };
    case "critical":
      return {
        label: "Critical",
        colorClass: "text-red-400",
        bgClass: "bg-red-500/10",
      };
    default:
      return {
        label: severity,
        colorClass: "text-gray-400",
        bgClass: "bg-gray-500/10",
      };
  }
}

/**
 * Get display properties for probability level
 */
export function getProbabilityDisplayProps(probability: string): {
  label: string;
  colorClass: string;
} {
  switch (probability.toLowerCase()) {
    case "unlikely":
      return {
        label: "Unlikely",
        colorClass: "text-green-400",
      };
    case "possible":
      return {
        label: "Possible",
        colorClass: "text-yellow-400",
      };
    case "likely":
      return {
        label: "Likely",
        colorClass: "text-orange-400",
      };
    case "very_likely":
      return {
        label: "Very Likely",
        colorClass: "text-red-400",
      };
    default:
      return {
        label: probability,
        colorClass: "text-gray-400",
      };
  }
}

/**
 * Get display properties for earnings predictability
 */
export function getEarningsPredictabilityDisplayProps(predictability: string): {
  label: string;
  colorClass: string;
  bgClass: string;
} {
  switch (predictability.toLowerCase()) {
    case "highly_predictable":
      return {
        label: "Highly Predictable",
        colorClass: "text-emerald-400",
        bgClass: "bg-emerald-500/10",
      };
    case "predictable":
      return {
        label: "Predictable",
        colorClass: "text-green-400",
        bgClass: "bg-green-500/10",
      };
    case "uncertain":
      return {
        label: "Uncertain",
        colorClass: "text-yellow-400",
        bgClass: "bg-yellow-500/10",
      };
    case "unpredictable":
      return {
        label: "Unpredictable",
        colorClass: "text-red-400",
        bgClass: "bg-red-500/10",
      };
    default:
      return {
        label: predictability,
        colorClass: "text-gray-400",
        bgClass: "bg-gray-500/10",
      };
  }
}

/**
 * Get investor type label for display
 */
export function getInvestorTypeLabel(type: string): string {
  switch (type.toLowerCase()) {
    case "value_investors":
      return "Value Investors";
    case "dividend_seekers":
      return "Dividend Seekers";
    case "growth_investors":
      return "Growth Investors";
    case "income_investors":
      return "Income Investors";
    case "long_term_holders":
      return "Long-Term Holders";
    case "conservative_investors":
      return "Conservative Investors";
    case "aggressive_investors":
      return "Aggressive Investors";
    default:
      return type.replace(/_/g, " ").replace(/\b\w/g, (l) => l.toUpperCase());
  }
}

/**
 * Format conviction level as percentage string
 */
export function formatConvictionLevel(level: number): string {
  return `${(level * 100).toFixed(0)}%`;
}

/**
 * Get color class for conviction level
 */
export function getConvictionColorClass(level: number): string {
  if (level >= 0.8) return "text-emerald-400";
  if (level >= 0.6) return "text-green-400";
  if (level >= 0.4) return "text-yellow-400";
  if (level >= 0.2) return "text-orange-400";
  return "text-red-400";
}
