"use client";

import {
  useQuery,
  useMutation,
  useQueryClient,
  UseQueryResult,
  UseMutationResult,
} from "@tanstack/react-query";
import { getAnalysis, refreshAnalysis } from "@/lib/api";
import type { WarrenBuffettAnalysis } from "@/types/analysis";

/**
 * Query Keys for AI Analysis React Query cache management
 */
export const analysisQueryKeys = {
  all: ["analyses"] as const,
  detail: (ticker: string) => [...analysisQueryKeys.all, ticker] as const,
};

/**
 * Cache Configuration for AI Analysis Data
 * AI analysis is expensive to generate and doesn't change rapidly
 */
const ANALYSIS_CACHE_CONFIG = {
  /** 10 minutes - analysis doesn't change rapidly */
  staleTime: 10 * 60 * 1000,
  /** 60 minutes - keep in cache for longer since generation is expensive */
  gcTime: 60 * 60 * 1000,
};

/**
 * Hook to fetch AI analysis for a stock
 *
 * Fetches the Warren Buffett-style investment memo generated by AI.
 * The analysis is cached for 10 minutes before being considered stale.
 *
 * @param ticker - Stock ticker symbol (e.g., 'AAPL')
 * @param enabled - Whether to enable the query (default: true)
 * @returns Query result with AI analysis data
 *
 * @example
 * ```tsx
 * const { data, isLoading, error } = useAIAnalysis('AAPL');
 *
 * if (isLoading) return <AnalysisSkeleton />;
 * if (error) return <ErrorMessage error={error} />;
 *
 * return <AIAnalysis analysis={data} />;
 * ```
 */
export function useAIAnalysis(
  ticker: string,
  enabled: boolean = true
): UseQueryResult<WarrenBuffettAnalysis, Error> {
  return useQuery({
    queryKey: analysisQueryKeys.detail(ticker),
    queryFn: () => getAnalysis(ticker),
    enabled: !!ticker && enabled,
    staleTime: ANALYSIS_CACHE_CONFIG.staleTime,
    gcTime: ANALYSIS_CACHE_CONFIG.gcTime,
    // Retry failed requests with exponential backoff
    // AI generation can take time, so we have more retries
    retry: 3,
    retryDelay: (attemptIndex) => Math.min(1000 * 2 ** attemptIndex, 30000),
  });
}

/**
 * Hook to force refresh AI analysis
 *
 * Triggers a new AI analysis generation, bypassing the cache.
 * This is an expensive operation that may take 30-60 seconds.
 *
 * @returns Mutation result with refresh function
 *
 * @example
 * ```tsx
 * const { mutate: refreshAnalysis, isPending } = useRefreshAnalysis();
 *
 * <Button
 *   onClick={() => refreshAnalysis('AAPL')}
 *   disabled={isPending}
 * >
 *   {isPending ? 'Generating Analysis...' : 'Refresh Analysis'}
 * </Button>
 * ```
 */
export function useRefreshAnalysis(): UseMutationResult<
  WarrenBuffettAnalysis,
  Error,
  string,
  unknown
> {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: (ticker: string) => refreshAnalysis(ticker),
    onSuccess: (data, ticker) => {
      // Update the cache with fresh data
      queryClient.setQueryData(analysisQueryKeys.detail(ticker), data);
    },
    onError: (error) => {
      console.error("Failed to refresh AI analysis:", error);
    },
  });
}

/**
 * Hook to prefetch AI analysis data
 *
 * Useful for hover prefetching on stock list.
 * Since AI analysis takes time to generate, prefetching can improve UX.
 *
 * @returns Function to prefetch analysis for a ticker
 *
 * @example
 * ```tsx
 * const prefetchAnalysis = usePrefetchAnalysis();
 *
 * <StockRow
 *   onMouseEnter={() => prefetchAnalysis('AAPL')}
 * />
 * ```
 */
export function usePrefetchAnalysis(): (ticker: string) => void {
  const queryClient = useQueryClient();

  return (ticker: string) => {
    queryClient.prefetchQuery({
      queryKey: analysisQueryKeys.detail(ticker),
      queryFn: () => getAnalysis(ticker),
      staleTime: ANALYSIS_CACHE_CONFIG.staleTime,
    });
  };
}

/**
 * Hook to invalidate AI analysis cache
 *
 * Forces refetch on next access without immediately triggering a new request.
 *
 * @returns Function to invalidate analysis cache for a ticker
 *
 * @example
 * ```tsx
 * const invalidateAnalysis = useInvalidateAnalysis();
 *
 * // Invalidate after some external event
 * await invalidateAnalysis('AAPL');
 * ```
 */
export function useInvalidateAnalysis(): (ticker: string) => Promise<void> {
  const queryClient = useQueryClient();

  return async (ticker: string) => {
    await queryClient.invalidateQueries({
      queryKey: analysisQueryKeys.detail(ticker),
    });
  };
}

/**
 * Hook to check if AI analysis exists in cache
 *
 * Useful for determining if we should show a loading state
 * or if data is already available.
 *
 * @param ticker - Stock ticker symbol
 * @returns Whether analysis data exists in cache
 */
export function useAnalysisExists(ticker: string): boolean {
  const queryClient = useQueryClient();
  const data = queryClient.getQueryData<WarrenBuffettAnalysis>(
    analysisQueryKeys.detail(ticker)
  );
  return data !== undefined;
}

export default useAIAnalysis;
